lib/smartbet_web/router.ex
defmodule SmartbetWeb.Router do
  use SmartbetWeb, :router
  import Phoenix.LiveView.Router

  import SmartbetWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SmartbetWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/server_dashboard", metrics: SmartbetWeb.Telemetry
    end
  end

  scope "/", SmartbetWeb do
    pipe_through :browser

    get "/", PageController, :index


    scope "/dashboard" do
      get "/", DashboardController, :index
      get "/scores", DashboardController, :scores
    end

  end

  scope "/", SmartbetWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SmartbetWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    get "/users/settings/edit_password", UserSettingsController, :edit_password
    get "/users/settings/edit_teams", UserSettingsController, :edit_teams
    get "/users/settings/edit_bet+settings", UserSettingsController, :edit_bet
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email


    live "/live_user_bets", UserBetsLive
    live "/live_dashboard", DashboardLive

    scope "/admin" do
      get "/user_bets/delete/:id", UserBetsController, :delete
      resources "/user_bets", UserBetsController, except: [:delete]
      get "/user_bets/:id/:bet_result", UserBetsController, :close_bet

      resources "/countries", CountryController
      resources "/basketball_teams", BasketballTeamController
      resources "/basketball_leagues", BasketballLeageController

      live "/live_console", AdminConsoleLive
      live "/live_console/basketball_league", BasketballLeagueLive
    end

  end

  scope "/", SmartbetWeb do
    pipe_through [:browser]

    get "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/smartbet_web/views/layout_view.ex
defmodule SmartbetWeb.LayoutView do
  use SmartbetWeb, :view
  import Phoenix.LiveView.Helpers
end

lib/smartbet_web/templates/layout/_user_menu.html.eex
<ul>
<%= if @current_user do %>
  <li><%= @current_user.email %></li>
  <li><%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Register", to: Routes.user_registration_path(@conn, :new) %></li>
  <li><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/smartbet_web/templates/layout/_user_menu.html.heex
<ul>
<%= if @current_user do %>
  <li><%= @current_user.email %></li>
  <li><%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Register", to: Routes.user_registration_path(@conn, :new) %></li>
  <li><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/smartbet_web/templates/layout/app.html.heex
<!--%= render "_user_menu.html", assigns %-->
<%= if assigns[:changeset] do %>
    <%= render(SmartbetWeb.DashboardView, "navbar.html", conn: @conn, changeset: @changeset) %>
<% end %>
<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

<div id="huro-app" class="app-wrapper">
    <%= @inner_content %>
</div>

lib/smartbet_web/templates/layout/dashboard_layout.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Smartbet</title>
    <%= csrf_meta_tag() %>
    <link rel="stylesheet" href={ Routes.static_path(@conn, "/css/app.css") }/>
    <link rel="stylesheet" href={ Routes.static_path(@conn, "/css/main.css") }/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Semi+Condensed:wght@400;600&display=swap" rel="stylesheet">
    <script defer type="text/javascript" src={ Routes.static_path(@conn, "/js/app.js") }></script>
    <link rel="icon" type="image/png" href={ Routes.static_path(@conn, "/images/favicon.png") }/>
  </head>
  <body>

    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

    <div id="huro-app" class="app-wrapper">
      <%= render(SmartbetWeb.DashboardView, "navbar.html", conn: @conn, changeset: @changeset) %>
      <%= @inner_content %>

    </div>  

    <!-- TMP1 -->
    <script src={ Routes.static_path(@conn, "/assets/app.js") } defer></script>
    <script src={ Routes.static_path(@conn, "/js/functions.js")} ></script>
    <script src={ Routes.static_path(@conn, "/js/main.js")}  async></script>
    <script src={ Routes.static_path(@conn, "/js/components.js")}  async></script>
    <script src={ Routes.static_path(@conn, "/js/popover.js")}  async></script>
    <script src={ Routes.static_path(@conn, "/js/widgets.js")}  async></script>
    <script src={ Routes.static_path(@conn, "/js/touch.js")}  async></script>
    <script src={ Routes.static_path(@conn, "/js/syntax.js")}  async></script>



  </body>
</html>

lib/smartbet_web/templates/layout/live.html.heex
<%= render(SmartbetWeb.DashboardView, "navbar.html", conn: @socket) %>

<div id="app-projects" class="view-wrapper is-webapp" data-page-title="Projects" data-naver-offset="214"
    data-menu-item="#layouts-navbar-menu" data-mobile-item="#home-sidebar-menu-mobile">

    <div class="page-content-wrapper">
      <div class="page-content is-relative">

        <%= if live_flash(@flash, :success) do %>
        <div class="message is-success">
          <a class="delete" phx-click="clear_flash"></a>
          <div class="alert alert-info message-body" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
            <%= live_flash(@flash, :success) %>
          </div>
        </div>
        <% end %>

        <%= if live_flash(@flash, :error) do %>
          <div class="message is-danger">
            <a class="delete" phx-click="clear_flash"></a>
            <div class="alert alert-info message-body" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
              <i class="lnil lnil-cross-cricle"></i>
              <%= live_flash(@flash, :error) %>
            </div>
          </div>
        <% end %>

        <%= @inner_content %>

        </div>
    </div>
</div>

lib/smartbet_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Smartbet</title>
      <%= csrf_meta_tag() %>
    <link rel="stylesheet" href={ Routes.static_path(@conn, "/css/app.css") }/>
    <link rel="stylesheet" href={ Routes.static_path(@conn, "/css/main.css") }/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Semi+Condensed:wght@400;600&display=swap" rel="stylesheet">
    <script defer type="text/javascript" src={ Routes.static_path(@conn, "/assets/app.js") }></script>
    <link rel="icon" type="image/png" href={ Routes.static_path(@conn, "/images/favicon.png") } />
  </head>
  <body>
    <%= @inner_content %>
 
    <script src={ Routes.static_path(@conn, "/js/app.js") } defer ></script>
    <script src={ Routes.static_path(@conn, "/js/functions.js") } defer ></script>
    <script src={ Routes.static_path(@conn, "/js/main.js") } async ></script>
    <script src={ Routes.static_path(@conn, "/js/widgets.js") } async></script>
    <script src={ Routes.static_path(@conn, "/js/touch.js") } async></script>
    <script src={ Routes.static_path(@conn, "/js/syntax.js") } async></script>
  </body>
</html>

lib/smartbet_web/templates/layout/user_live.html.heex
<p>USER</p>
<div id="app-projects" class="view-wrapper is-webapp" data-page-title="Projects" data-naver-offset="214"
    data-menu-item="#layouts-navbar-menu" data-mobile-item="#home-sidebar-menu-mobile">

    <div class="page-content-wrapper">
        <div class="page-content is-relative">

  <%= if live_flash(@flash, :success) do %>
  <div class="message is-success">
    <a class="delete" phx-click="clear_flash"></a>
    <div class="alert alert-info message-body" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
      <%= live_flash(@flash, :success) %>
    </div>
  </div>
  <% end %>

  <%= if live_flash(@flash, :error) do %>
    <div class="message is-danger">
      <a class="delete" phx-click="clear_flash"></a>
      <div class="alert alert-info message-body" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
        <i class="lnil lnil-cross-cricle"></i>
        <%= live_flash(@flash, :error) %>
      </div>
    </div>
  <% end %>

  <%= live_render(@socket, SmartbetWeb.NavbarLive, id: "navbar") %>

  <%= @inner_content %>
<!-- TMP4 -->
  <script src={ Routes.static_path(@socket, "/js/app.js" )} async ></script>
  <script src={ Routes.static_path(@socket, "/js/main.js" )} async></script>
  <script src={ Routes.static_path(@socket, "/js/functions.js" )} async></script>
  <script src={ Routes.static_path(@socket, "/js/components.js" )} async></script>
  <script src={ Routes.static_path(@socket, "/js/popover.js" )} async></script>
  <script src={ Routes.static_path(@socket, "/js/widgets.js" )} async></script>
  <script src={ Routes.static_path(@socket, "/js/touch.js" )} async></script>
  <script src={ Routes.static_path(@socket, "/js/syntax.js" )} async></script>


        </div>
    </div>
</div>