lib/smartbet_web/router.ex
defmodule SmartbetWeb.Router do
  use SmartbetWeb, :router
  import Phoenix.LiveView.Router

  import SmartbetWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SmartbetWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/server_dashboard", metrics: SmartbetWeb.Telemetry
    end
  end

  scope "/", SmartbetWeb do
    pipe_through :browser

    get "/", PageController, :index


    scope "/dashboard" do
      get "/", DashboardController, :index
      get "/scores", DashboardController, :scores
    end

  end

  scope "/", SmartbetWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SmartbetWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    get "/users/settings/edit_password", UserSettingsController, :edit_password
    get "/users/settings/edit_teams", UserSettingsController, :edit_teams
    get "/users/settings/edit_bet+settings", UserSettingsController, :edit_bet
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email


    live "/live_user_bets", UserBetsLive
    live "/live_dashboard", DashboardLive

    scope "/admin" do
      get "/user_bets/delete/:id", UserBetsController, :delete
      resources "/user_bets", UserBetsController, except: [:delete]
      get "/user_bets/:id/:bet_result", UserBetsController, :close_bet

      resources "/countries", CountryController
      resources "/basketball_teams", BasketballTeamController
      resources "/basketball_leagues", BasketballLeageController

      live "/live_console", AdminConsoleLive
      live "/live_console/basketball_league", BasketballLeagueLive
    end

  end

  scope "/", SmartbetWeb do
    pipe_through [:browser]

    get "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/smartbet_web/controllers/user_session_controller.ex
defmodule SmartbetWeb.UserSessionController do
  use SmartbetWeb, :controller

  alias Smartbet.Accounts
  alias SmartbetWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/smartbet_web/views/user_session_view.ex
defmodule SmartbetWeb.UserSessionView do
  use SmartbetWeb, :view
end

lib/smartbet_web/templates/user_session/new.html.heex
<!--Full pageloader-->
<!-- Pageloader -->
<div class="pageloader is-full"></div>
<div class="infraloader is-full is-active"></div>
<div class="auth-wrapper">
    <!--Page body-->

    <div class="auth-wrapper-inner is-single">

        <!--Fake navigation-->
        <div class="auth-nav">
            <div class="left"></div>
            <div class="center">
                <a href="/" class="header-item">
                    <img class="light-image" src="assets/img/logos/logo/logo.svg" alt="">
                    <img class="dark-image" src="assets/img/logos/logo/logo-light.svg" alt="">
                </a>
            </div>
            <div class="right">
                <label class="dark-mode ml-auto">
                    <input type="checkbox" checked>
                    <span></span>
                </label>
            </div>
        </div>

        <!--Single Centered Form-->
        <div class="single-form-wrap">

            <div class="inner-wrap">
                <!--Form Title-->
                <div class="auth-head">
                    <h2>Welcome Back.</h2>
                    <p>Please sign in to your account</p>
                    <%= link "I do not have an account yet" , to: Routes.user_registration_path(@conn, :new) %>
                </div>

                <!--Form-->
                <div class="form-card">
                    <%= form_for @conn, Routes.user_session_path(@conn, :create), [as: :user], fn f -> %>
                        <form>
                            <div id="signin-form" class="login-form">
                                <!-- Input -->
                                <div class="field">
                                    <div class="control has-icon">
                                        <!--input class="input" type="text" placeholder="Username"-->
                                        <%= email_input f, :email, required: true, class: "input" , placeholder: "Email"
                                            %>
                                            <span class="form-icon">
                                                <i data-feather="user"></i>
                                            </span>
                                    </div>
                                </div>
                                <!-- Input -->
                                <div class="field">
                                    <div class="control has-icon">
                                        <!--input class="input" type="password" placeholder="Password"-->
                                        <%= password_input f, :password, required: true, class: "input" ,
                                            placeholder: "Password" %>
                                            <span class="form-icon">
                                                <i data-feather="lock"></i>
                                            </span>
                                    </div>
                                </div>

                                <%= if @error_message do %>
                                    <div class="has-text-danger has-text-centered">
                                        <span>
                                            <%= @error_message %>
                                        </span>
                                    </div>
                                    <% end %>

                                        <div class="setting-item">
                                            <label class="form-switch is-primary">
                                                <input type="checkbox" class="is-switch" id="busy-mode-toggle">
                                                <%= checkbox f, :remember_me %>
                                                    <i></i>
                                            </label>
                                            <div class="setting-meta">
                                                <span>
                                                    <%= label f, :remember_me, "Keep me logged in for 60 days" %>
                                                </span>
                                            </div>
                                        </div>

                                        <!-- Submit -->
                                        <div class="control login">
                                            <%= submit "Log in" ,
                                                class: "button h-button is-primary is-bold is-fullwidth is-raised" %>
                                        </div>


                            </div>
                        </form>

                        <% end %>
                </div>

                <div class="forgot-link has-text-centered">
                    <%= link "Forgot your password?" , to: Routes.user_reset_password_path(@conn, :new) %>
                </div>

            </div>

        </div>

    </div>
</div>
 